<a href="https://colab.research.google.com/github/ednamilgo/EASY_ML/blob/main/Python_1(d)_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

In [1]:
import numpy as np

## Creating numpy array from list

In [2]:
# Creating a numpy array from a list
mylist=[23,67,78,5]

In [3]:
my_np_list = np.array(mylist) # creating np array from a list
my_np_list

array([23, 67, 78,  5])

In [4]:
## Another way of creating from a list
marks1 =np.array([69,78,90,87])
marks1

array([69, 78, 90, 87])

## 1D array

In [5]:
array2 = np.array([2,-7.4,6,7.2])
array2

array([ 2. , -7.4,  6. ,  7.2])

# 2D array

In [6]:
marks2 =np.array([[69,78,90,87],[98,76,77,86], [88,77,67,99]]) # creating a 2D array
marks2

array([[69, 78, 90, 87],
       [98, 76, 77, 86],
       [88, 77, 67, 99]])

## Slicing array 1D array

In [7]:
mylist[:-1]

[23, 67, 78]

## Slicing array 2D array-- row,column

In [8]:
marks2[1,:]

array([98, 76, 77, 86])

In [9]:
marks2[:,1]

array([78, 76, 77])

In [10]:
marks2[1,0:2]

array([98, 76])

In [11]:
marks2[2,1:4]

array([77, 67, 99])

In [12]:
marks2[2,1:4]

array([77, 67, 99])

In [13]:
marks2[2,1:4]

array([77, 67, 99])

In [14]:
marks2[2,1:]

array([77, 67, 99])

In [15]:
marks2[1:3,2:3]

array([[77],
       [67]])

## Append

In [16]:
new_np_list= np.append(my_np_list, [44,55])
new_np_list

array([23, 67, 78,  5, 44, 55])

## Sorting an array

In [17]:
np.sort(new_np_list) # Ascending order

array([ 5, 23, 44, 55, 67, 78])

In [18]:
np.sort(new_np_list)[::-1] # descending order

array([78, 67, 55, 44, 23,  5])

In [19]:
ReversedArraySort = np.sort(new_np_list)[::-1]
ReversedArraySort

array([78, 67, 55, 44, 23,  5])

## Reshaping Arrays

In [20]:
array1 = np.arange(10,22)
array1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [21]:
array2 = array1.reshape(3,4) #reshape
array2

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

# Statistical functions

In [22]:
np.mean(new_np_list)

np.float64(45.333333333333336)

In [23]:
np.max(new_np_list)

np.int64(78)